In [34]:
report = {
    "Predicted Disease": top_disease,
    "Disease Probability": f"{top_probability * 100:.2f}%",
    "Severity": severity,
    "Risk Score": risk_score,
    "Risk Level": risk_level
}

for key, value in report.items():
    print(f"{key}: {value}")

Predicted Disease: Pneumonia
Disease Probability: 52.00%
Severity: Medium
Risk Score: 8
Risk Level: Medium

In [33]:
severity = calculate_severity(
    fever=1,
    cough=1,
    fatigue=0,
    difficulty_breathing=0
)

risk_score = calculate_risk_score(
    age=45,
    blood_pressure="Normal",
    cholesterol="High",
    severity=severity
)

risk_level = get_risk_level(risk_score)

print("Severity:", severity)
print("Risk Score:", risk_score)
print("Risk Level:", risk_level)

Severity: Medium
Risk Score: 8
Risk Level: Medium

In [32]:
def get_risk_level(score):
    if score <= 4:
        return "Low"
    elif score <= 8:
        return "Medium"
    else:
        return "High"


print("Risk level function updated successfully!")

Risk level function updated successfully!

In [31]:
severity = calculate_severity(
    fever=1,
    cough=1,
    fatigue=0,
    difficulty_breathing=0
)

risk_score = calculate_risk_score(
    age=45,
    blood_pressure="Normal",
    cholesterol="High",
    severity=severity
)

risk_level = get_risk_level(risk_score)

print("Severity:", severity)
print("Risk Score:", risk_score)
print("Risk Level:", risk_level)

Severity: Medium
Risk Score: 8
Risk Level: High

In [30]:
severity = calculate_severity(
    fever=0,
    cough=0,
    fatigue=1,
    difficulty_breathing=0
)

risk_score = calculate_risk_score(
    age=25,
    blood_pressure="Normal",
    cholesterol="Normal",
    severity=severity
)

risk_level = get_risk_level(risk_score)

print("Severity:", severity)
print("Risk Score:", risk_score)
print("Risk Level:", risk_level)

Severity: Low
Risk Score: 3
Risk Level: Low

In [29]:
severity = calculate_severity(
    fever=1,
    cough=1,
    fatigue=1,
    difficulty_breathing=1
)

risk_score = calculate_risk_score(
    age=55,
    blood_pressure="High",
    cholesterol="High",
    severity=severity
)

risk_level = get_risk_level(risk_score)

print("Severity:", severity)
print("Risk Score:", risk_score)
print("Risk Level:", risk_level)

Severity: High
Risk Score: 11
Risk Level: High

In [28]:
def get_risk_level(score):
    if score <= 4:
        return "Low"
    elif score <= 7:
        return "Medium"
    else:
        return "High"


print("Risk level function created successfully!")

Risk level function created successfully!

In [27]:
def calculate_risk_score(age, blood_pressure, cholesterol, severity):
    score = 0

    # Age risk
    if age >= 60:
        score += 3
    elif age >= 40:
        score += 2
    elif age >= 30:
        score += 1

    # Blood pressure risk
    if blood_pressure == "High":
        score += 3
    elif blood_pressure == "Normal":
        score += 1

    # Cholesterol risk
    if cholesterol == "High":
        score += 3
    elif cholesterol == "Normal":
        score += 1

    # Symptom severity
    if severity == "High":
        score += 3
    elif severity == "Medium":
        score += 2
    else:
        score += 1

    return score


print("Risk scoring function created successfully!")

Risk scoring function created successfully!

In [26]:
def calculate_severity(fever, cough, fatigue, difficulty_breathing):
    score = fever + cough + fatigue + difficulty_breathing

    if score <= 1:
        return "Low"
    elif score <= 2:
        return "Medium"
    else:
        return "High"


print("Severity function created successfully!")

Severity function created successfully!

In [25]:
import os

print("Model exists:", os.path.exists("../../backend/models/disease_model.pkl"))
print("Label encoder exists:", os.path.exists("../../backend/models/label_encoder.pkl"))

Model exists: True
Label encoder exists: True

In [24]:
import joblib

joblib.dump(model, "../../backend/models/disease_model.pkl")
joblib.dump(label_encoder, "../../backend/models/label_encoder.pkl")

print("Model and label encoder saved successfully!")

Model and label encoder saved successfully!

In [23]:
top_3_indices = np.argsort(probabilities[0])[-3:][::-1]

for index in top_3_indices:
    disease = label_encoder.inverse_transform([model.classes_[index]])[0]
    probability = probabilities[0][index]

    print(f"{disease}: {probability * 100:.2f}%")

Pneumonia: 52.00%
Osteoarthritis: 7.00%
Asthma: 6.67%

In [22]:
import numpy as np

top_index = np.argmax(probabilities[0])
top_probability = probabilities[0][top_index]

top_disease = label_encoder.inverse_transform(
    [model.classes_[top_index]]
)[0]

print("Top predicted disease:", top_disease)
print("Probability:", top_probability)
print("Probability percentage:", top_probability * 100, "%")

Top predicted disease: Pneumonia
Probability: 0.52
Probability percentage: 52.0 %

In [21]:
probabilities = model.predict_proba(X_test)

print("Probability shape:", probabilities.shape)
print("First prediction probabilities:")
print(probabilities[0])

Probability shape: (60, 102)
First prediction probabilities:
[0.         0.01       0.         0.         0.01       0.
 0.06666667 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.005      0.         0.         0.
 0.06       0.         0.         0.         0.         0.01
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.01333333 0.06083333
 0.03       0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.07       0.         0.         0.         0.
 0.         0.05916667 0.         0.005      0.52       0.02
 0.         0.         0.         0.         0.02       0.
 0.         0.         0.01       0.         0.         0.
 0.01       0.         0.         0.         0.         0.
 0.         0.         0.         0.02       0.         0.        ]

In [20]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

Model Accuracy: 0.05
Accuracy Percentage: 5.0 %

c:\Users\sallo\MedAssist-AI\.venv\lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\sallo\MedAssist-AI\.venv\lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")

In [19]:
predicted_diseases = label_encoder.inverse_transform(y_pred)

print("First 10 predicted diseases:")
print(predicted_diseases[:10])

First 10 predicted diseases:
['Pneumonia' "Crohn's Disease" 'Kidney Cancer' 'Influenza'
 'Coronary Artery Disease' 'Polycystic Ovary Syndrome (PCOS)' 'Bronchitis'
 'Asthma' 'Liver Cancer' 'Hemorrhoids']

In [18]:
y_pred = model.predict(X_test)

print("Predictions generated!")
print("First 10 predictions:", y_pred[:10])

Predictions generated!
First 10 predictions: [84 27 57 56 26 87 13  6 60 47]

In [17]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (240, 15)
X_test: (60, 15)
y_train: (240,)
y_test: (60,)

In [15]:
print(y.value_counts().describe())
print("\nDiseases with only 1 record:")
print(y.value_counts()[y.value_counts() == 1])

count    116.000000
mean       2.586207
std        2.840909
min        1.000000
25%        1.000000
50%        1.000000
75%        3.000000
max       16.000000
Name: count, dtype: float64

Diseases with only 1 record:
Disease
Atherosclerosis                    1
Bipolar Disorder                   1
Cirrhosis                          1
Rubella                            1
Myocardial Infarction (Heart...    1
                                  ..
Schizophrenia                      1
Gout                               1
Testicular Cancer                  1
Tonsillitis                        1
Williams Syndrome                  1
Name: count, Length: 77, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Number of diseases:", len(label_encoder.classes_))
print("First 10 encoded labels:", y_encoded[:10])

Number of diseases: 116
First 10 encoded labels: [56 24 37  6 37 56 53  6  1  4]

In [13]:
X = df.drop("Disease", axis=1)
y = df["Disease"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (300, 15)
y shape: (300,)

In [12]:
df = pd.get_dummies(
    df,
    columns=["Gender", "Blood Pressure", "Cholesterol Level", "Outcome Variable"],
    dtype=int
)

df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender_Female,Gender_Male,Blood Pressure_High,Blood Pressure_Low,Blood Pressure_Normal,Cholesterol Level_High,Cholesterol Level_Low,Cholesterol Level_Normal,Outcome Variable_Negative,Outcome Variable_Positive
0,Influenza,1,0,1,1,19,1,0,0,1,0,0,0,1,0,1
1,Common Cold,0,1,1,0,25,1,0,0,0,1,0,0,1,1,0
2,Eczema,0,1,1,0,25,1,0,0,0,1,0,0,1,1,0
3,Asthma,1,1,0,1,25,0,1,0,0,1,0,0,1,0,1
4,Eczema,1,0,0,0,25,1,0,0,0,1,0,0,1,0,1

In [11]:
df["Fever"] = df["Fever"].map({"Yes": 1, "No": 0})
df["Cough"] = df["Cough"].map({"Yes": 1, "No": 0})
df["Fatigue"] = df["Fatigue"].map({"Yes": 1, "No": 0})
df["Difficulty Breathing"] = df["Difficulty Breathing"].map({"Yes": 1, "No": 0})

df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,1,0,1,1,19,Female,Low,Normal,Positive
1,Common Cold,0,1,1,0,25,Female,Normal,Normal,Negative
2,Eczema,0,1,1,0,25,Female,Normal,Normal,Negative
3,Asthma,1,1,0,1,25,Male,Normal,Normal,Positive
4,Eczema,1,0,0,0,25,Female,Normal,Normal,Positive

In [10]:
df[["Fever", "Cough", "Fatigue", "Difficulty Breathing"]].head()

  Fever Cough Fatigue Difficulty Breathing
0   Yes    No     Yes                  Yes
1    No   Yes     Yes                   No
2    No   Yes     Yes                   No
3   Yes   Yes      No                  Yes
4   Yes    No      No                   No

In [9]:
df["Disease"].value_counts()

Disease
Asthma               16
Osteoporosis         12
Stroke               11
Diabetes             10
Hypertension         10
                     ..
Schizophrenia         1
Gout                  1
Testicular Cancer     1
Tonsillitis           1
Williams Syndrome     1
Name: count, Length: 116, dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Disease               300 non-null    object
 1   Fever                 300 non-null    object
 2   Cough                 300 non-null    object
 3   Fatigue               300 non-null    object
 4   Difficulty Breathing  300 non-null    object
 5   Age                   300 non-null    int64
 6   Gender                300 non-null    object
 7   Blood Pressure        300 non-null    object
 8   Cholesterol Level     300 non-null    object
 9   Outcome Variable      300 non-null    object
dtypes: int64(1), object(9)
memory usage: 23.6+ KB

In [4]:
df = pd.read_csv("../../cleaned_dataset.csv")

df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,19,Female,Low,Normal,Positive
1,Common Cold,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
2,Eczema,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Eczema,Yes,No,No,No,25,Female,Normal,Normal,Positive

In [2]:
import pandas as pd
import numpy as np